@base_url=http://localhost:8081
# @name auth

GET {{base_url}}/tokenz

@token= {{auth.response.body.$.token}}

@idParam=2

###
DELETE  {{base_url}}/todos/{{idParam}}
Content-Type: application/json
Authorization: Bearer {{token}}

